version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://nainu8700:Nainu%40123@cluster0.c4bem.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongodb

  frontend:
       build: ./frontend
       ports:
         - "3001:3001"
       environment:
         - PORT=3001
       depends_on:
         - backend

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: